# Generated by Django 5.1 on 2024-08-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
