# Generated by Django 5.1 on 2024-08-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeapp", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="zone",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
