# Generated by Django 5.1 on 2024-08-17 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeapp", "0005_alter_area_name_alter_state_name_alter_unit_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("coordinates", models.JSONField()),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pipeapp.state"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PipelineFault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fault_coordinates", models.JSONField()),
                ("description", models.TextField(blank=True, null=True)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pipeline_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faults",
                        to="pipeapp.pipelineroute",
                    ),
                ),
            ],
        ),
    ]
