# Generated by Django 5.1 on 2024-08-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeapp", "0006_pipelineroute_pipelinefault"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinefault",
            name="status",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("warning", "Warning"),
                    ("critical", "Critical"),
                ],
                default="normal",
                max_length=10,
            ),
        ),
    ]
